FROM postgres:11.2

ENV POSTGRES_USER=todo
ENV POSTGRES_DB=todo
# Do not set POSTGRES_PASSWORD here; pass it securely at runtime using environment variables.

COPY CreateTodoTable.sql /docker-entrypoint-initdb.d/